"""Synthesis Layer — Agent State.

Defines the TypedDict state used by the LangGraph reflexive state machine.
"""

from __future__ import annotations

from typing import Annotated, TypedDict

from chronos_link.perception.models import ProjectDNA
from chronos_link.temporal.models import TemporalContext


def _merge_last(old: str, new: str) -> str:
    """Simple merger that keeps the latest string (for graph state)."""
    return new


class AgentState(TypedDict):
    """Internal state of the Chronos-Link-V1 synthesis agent.

    Attributes:
        project_dna: Result of Phase 1 (Perception Layer).
        temporal_context: Result of Phase 2 (Temporal Layer).
        draft_adr: The raw markdown draft generated by the Actor.
        critique: Feedback provided by the Critic.
        final_adr: The polished markdown ready for storage.
        iteration: Current Actor-Critic loop count.
        max_iterations: Safety limit for loops.
        is_valid: Flag set by the Critic to signal acceptance.
    """

    project_dna: ProjectDNA
    temporal_context: TemporalContext
    
    # State updates
    draft_adr: Annotated[str, _merge_last]
    critique: Annotated[str, _merge_last]
    final_adr: Annotated[str, _merge_last]
    
    iteration: Annotated[int, lambda old, new: old + new]
    max_iterations: int
    is_valid: Annotated[bool, _merge_last]
